export type MessageType =
  | "PLAYER_JOINED"
  | "PLAYER_LEFT"
  | "PLAYER_PROGRESS"
  | "GAME_OVER"
  | "GAME_RESTART"
  | "GAME_STARTED"
  | "TYPING_UPDATE"
  | "PLAYER_FINISHED"
  | "ROOM_UPDATE";
